################################################################################################################  
###内置应用容器（Tomcat）配置：  
################################################################################################################
server:
  port: 8084
  servlet:
    context-path: /
    session:
      timeout: 1800

################################################################################################################  
###接口文档（Swagger UI）配置：  
################################################################################################################
swagger:
  enabled: true
  title: Jeebiz Boot Demo
  description: Jeebiz Boot Demo
  version: 0.0.1-SNAPSHOT
  license: Apache License, Version 2.0
  license-url: https://www.apache.org/licenses/LICENSE-2.0.html
  contact:
    name: 杭州极蚁网络科技有限公司
    email: hiwepy@163.com
    url: http://www.hiwepy.com/
  base-package: net.jeebiz
  base-path:
  - /**
  exclude-path:
  - /error
  - /ops/**

################################################################################################################  
###Shiro 权限控制基本配置：  
################################################################################################################
shiro:
  annotations: 
    enabled: true
    proxy-target-class: true
  cache:
    type: ehcache
  enabled: true
  kaptcha:
    enabled: true
    retry-times-when-access-denied: 3
  failure-url: /error
  login-url: /authz/login/slogin
  redirect-url: /authz/login/index
  success-url: /index
  unauthorized-url: /error
  user-native-session-manager: true
  session-creation-enabled: true
  session-validation-scheduler-enabled: true
  session-validation-interval: 20000
  session-stateless: false
  session-storage-enabled: true
  session-timeout: 1800000
  web: 
    enabled: true
  filter-chain-definition-map: 
    '[/]' : anon
    '[/**/favicon.ico]' : anon
    '[/webjars/**]' : anon
    '[/assets/**]' : anon
    '[/error*]' : anon
    '[/logo/**]' : anon
    '[/swagger-ui.html**]' : anon
    '[/swagger-resources/**]' : anon
    '[/v2/**]' : anon
    '[/kaptcha*]' : anon
    '[/sockets/**]' : anon
    '[/authz/login/slogin]' : authc
    '[/logout]' : logout
    '[/**]' : authc

################################################################################################################  
###Spring Boot 相关组件（SpringMVC、Freemarker、Session、Cache、DataSource）配置：  
################################################################################################################
spring: 
  messages:
    #指定message的basename，多个以逗号分隔，如果不加包名的话，默认从classpath路径开始，默认: messages
    basename: i18n/*/messages,i18n/messages
    #设定加载的资源文件缓存失效时间，-1的话为永不过期，默认为-1
    #cache-seconds: 6000
    #设定Message bundles的编码，默认: UTF-8
    encoding: UTF-8
    
  profiles:
    active: dev
  
  #MVC
  mvc:
    static-path-pattern: /**
    view:
      prefix: classpath:/templates/
  resources:
    static-locations:
    - classpath:/templates/
  #thymelea模板配置：https://www.thymeleaf.org/doc/tutorials/3.0/usingthymeleaf.html
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
  
  # 会话配置（交给Shiro管理，此处不再指定）：
  session: 
    store-type: none    
    
  # 缓存配置：
  cache: 
    type: ehcache
    ehcache:
      config: classpath:/conf/ehcache/ehcache.xml

  # 数据源配置：
  datasource:
    name: jeebiz_demo
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.43.110.87:3306/jeebiz_demo?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8
    username: jeebiz_demo
    password: ntzre47GiAJnL3AS
    # Druid的数据源配置：
    druid: 
      enabled: true
      #配置这个属性的意义在于，如果存在多个数据源，监控的时候可以通过名字来区分开来。如果没有配置，将会生成一个名字，格式是：”DataSource-” + System.identityHashCode(this)
      #name: DataSource-Test
      #这一项可配可不配，如果不配置druid会根据url自动识别dbType，然后选择相应的driverClassName
      #driver-class-name: oracle.jdbc.driver.OracleDriver         
      #url: 
      #username: xxx
      #password: xxx 
      #initialSize: 初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时；默认 15
      initial-size: 15
      #连接池最大连接数量 
      max-active: 50
      #获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁
      max-wait: 60000
      #连接池最小连接数量；默认 5
      min-idle: 5
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒;有两个含义：1) Destroy线程会检测连接的间隔时间 2) testWhileIdle的判断依据，详细看testWhileIdle属性的说明
      time-between-eviction-runs-millis: 60000
      #配置一个连接在池中最小生存的时间，单位：毫秒
      min-evictable-idle-time-millis: 300000
      #超过时间限制是否回收
      remove-abandoned: true
      #超过时间限制多长，单位：毫秒 ，180000毫秒=3分钟
      remove-abandoned-timeout-millis: 180000
      #用来检测连接是否有效的sql，要求是一个查询语句。如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会其作用。
      validation-query: SELECT 1 FROM DUAL
      #申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。建议配置为true，不影响性能，并且保证安全性。
      test-while-idle: true
      #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-borrow: false
      # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      test-on-return: false
      #是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql5.5以下的版本中没有PSCache功能，建议关闭掉。5.5及以上版本有PSCache，建议开启。 
      pool-prepared-statements: true
      #要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100 
      max-pool-prepared-statement-per-connection-size: 100
      #Druid的监控统计功能:属性类型是字符串，通过别名的方式配置扩展插件
      #filters: mergeStat,wall,slf4j
      # 动态数据源
      routable: true
      # Druid监控配置
      aop-patterns:
      - net.jeebiz.boot.demo.web.mvc
      stat-view-servlet:
        enabled: true
        reset-enable: false
      web-stat-filter:
        enabled: true
        session-stat-enable: true
        session-stat-max-count: 20000
      # Druid自定义过滤器参数
      filter:
        # 配置日志输出
        slf4j:
          enabled: true
          statement-create-after-log-enabled: false
          statement-close-after-log-enabled: false
          result-set-open-after-log-enabled: false
          result-set-close-after-log-enabled: false
        # 配置安全防护
        wall:
          # 对被认为是攻击的SQL进行LOG.error输出
          log-violation: true
          # 对被认为是攻击的SQL抛出SQLExcepton
          throw-exception: true
          config:
            # 是否允许语句中存在注释，Oracle的用户不用担心，Wall能够识别hints和注释的区别
            comment-allow: true
            # 是否允许非以上基本语句的其他语句，缺省关闭，通过这个选项就能够屏蔽DDL
            none-base-statement-allow: true
            # 是否允许一次执行多条语句，缺省关闭 
            multi-statement-allow: true
            # 解除union关键字检查
            select-union-check: false
            # 是否允许执行锁定表操作
            lock-table-allow: true
      
################################################################################################################  
###Flyway (FlywayMigrationProperties) 数据库迁移脚本版本管理（实现软件版本升级数据库自动升级）配置：  
################################################################################################################  
  flyway: 
    enabled: true
    locations:
    - classpath:db/migration/{vendor}
    #指定SQL起始版本信息 
    baseline-on-migrate: true
    baseline-version: 1.0.0.0
    baseline-description: 业务框架、权限管理、日志管理初始化
    #如果已经有版本1和3，当发现新的版本2时，如果此参数为true,将会把版本2作为当前版本  
    out-of-order: false
    #在进行版本升级前是否进行SQL版本信息校验
    validate-on-migrate: true
    #设置如果验证失败是否删除表结构
    clean-on-validation-error: true
    #禁止对数据库进行相关清除操作
    clean-disabled: true

################################################################################################################  
###mybatis-plus (MybatisPlusProperties) 基本配置：  
###http://mp.baomidou.com/#/spring-boot
################################################################################################################  
mybatis-plus:
  # 初始配置文件
  check-config-location: true 
  # config-location: classpath:/conf/mybatis/sqlMapConfig.xml
  #configuration-properties:
  # 初始配置参数
  #configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId） 
    #map-underscore-to-camel-case: true
    #cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    #jdbc-type-for-null: 'null'
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath*:net/jeebiz/**/dao/**/sqlmap/mysql/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: net.jeebiz.**.dao.entities
  configuration:
    # 指定MyBatis如何自动映射列到字段/属性。PARTIAL只会自动映射简单，没有嵌套的结果。
    # FULL会自动映射任意复杂的结果（嵌套的或其他情况）;有效值：NONE,PARTIAL,FULL,默认值：PARTIAL
    auto-mapping-behavior: partial
    # 当检测出未知列（或未知属性）时，如何处理，    默认情况下没有任何提示，这在测试的时候很不方便，不容易找到错误 
    auto-mapping-unknown-column-behavior: failing
    # 当启用时，使用延迟加载属性的对象在发起任何延迟属性的调用时会被完全加载。否则，每个属性在请求时就加载。默认值：true
    aggressive-lazy-loading: true
    # 全局二级缓存开关：默认是true，如果它配成false，其余各个Mapper XML文件配成支持cache也没用
    cache-enabled: true
    call-setters-on-nulls: false
    # database-id:  
    # default-fetch-size: 
    # 设置超时时间，它决定驱动等待一个数据库响应的时间。有效值：Any，positive，integer ；默认值：Not Set(null)
    default-statement-timeout: 25
    # 配置默认的执行器。SIMPLE 执行器没有什么特别之处。REUSE执行器重用预处理语句。BATCH 执行器重用语句和批量更新
    # 有效值：SIMPLE,REUSE,BATCH;默认值：SIMPLE
    default-executor-type: reuse
    jdbc-type-for-null: null
    map-underscore-to-camel-case: false
    # 允许或不允许多种结果集从一个单独的语句中返回（需要适合的驱动）;有效值：true,false;默认值：true
    multiple-result-sets-enabled: true
    #use-actual-param-name:
    # 使用列标签代替列名。不同的驱动在这方便表现不同。参考驱动文档或充分测试两种方法来决定所使用的驱动。有效值：true,false;默认值：true
    use-column-label: true 
    # 允许JDBC支持生成的键。需要适合的驱动。如果设置为true则这个设置强制生成的键被使用，尽管一些驱动拒绝兼容但仍然有效（比如 Derby）;有效值：true,false;默认值：false
    use-generated-keys: false
    safe-row-bounds-enabled: false
    safe-result-handler-enabled: true
    # 全局地禁用或启用延迟加载。禁用时，所有关联查询会被马上加载;默认值：true
    lazy-loading-enabled: true
    lazy-load-trigger-methods: 
      equals
      clone
      hashCode
      toString
    local-cache-scope: session
    log-prefix: "[Mybatis]"
    #log-impl: org.apache.ibatis.logging.log4j2.Log4j2LoggerImpl.class
    
  global-config: 
    sql-parser-cache: true
    db-config:
      id-type: auto
      field-strategy: not-empty
      #mp2.3+ 全局表前缀 mp_
      #table-prefix: mp_
      #刷新mapper 调试神器
      #refresh-mapper: true
      #数据库大写下划线转换
      #capital-mode: true
      # Sequence序列接口实现类配置
      #key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
      #逻辑删除配置（下面3个配置）
      logic-delete-value: 1
      logic-not-delete-value: 0
  
################################################################################################################  
###logging (log4j2) 基本配置：  
###http://www.cnblogs.com/yhtboke/p/Mybatis.html
################################################################################################################
logging: 
  config: classpath:conf/log4j2.xml
  