
DELETE FROM SYS_AUTHZ_ROLE_LIST;
INSERT INTO SYS_AUTHZ_ROLE_LIST ( R_ID, R_NAME, R_TYPE, R_INTRO, R_STATUS)
VALUES ( '1', '超级管理员', '1', '系统初始化的最高权限用户', '1' );
INSERT INTO SYS_AUTHZ_ROLE_LIST ( R_ID, R_NAME, R_TYPE, R_INTRO, R_STATUS)
VALUES ( '2', '普通管理员', '1', '普通功能管理员', '1' );
INSERT INTO SYS_AUTHZ_ROLE_LIST ( R_ID, R_NAME, R_TYPE, R_INTRO, R_STATUS)
VALUES ( '3', '普通用户', '1', '一般系统用户', '1' );

DELETE FROM SYS_AUTHZ_ROLE_PERMS;
INSERT INTO SYS_AUTHZ_ROLE_PERMS ( R_ID, PERMS)
VALUES ( '1', '*');

DELETE FROM SYS_AUTHZ_USER_LIST;
INSERT INTO SYS_AUTHZ_USER_LIST ( U_ID, U_USERNAME, U_PASSWORD, U_SALT, U_SECRET, U_ALIAS, U_AVATAR, U_PHONE, U_EMAIL, U_REMARK, U_STATUS  )
VALUES ( '1', 'admin', '123456', 'MTIzNDU2', 'MTIzNDU2', '超级管理员', '','13735896863', 'jeebiz@163.com', '默认最高权限管理员', '1');

DELETE FROM SYS_AUTHZ_USER_DETAIL;
INSERT INTO SYS_AUTHZ_USER_DETAIL ( U_ID, D_ID, D_BIRTHDAY, D_GENDER, D_IDCARD)
VALUES ( '1', '1', '1989-10-01', 'male', '411526198910010001');

DELETE FROM SYS_AUTHZ_USER_ROLE_RELATION;
INSERT INTO SYS_AUTHZ_USER_ROLE_RELATION ( U_ID, R_ID, R_PRTY)
VALUES ( '1', '1', '0');

INSERT INTO SYS_FEATURE_LIST (F_ID, F_NAME, F_ABB, F_CODE, F_URL, F_TYPE, F_ICON, F_PARENT, F_VISIBLE, F_ORDER) 
VALUES ('19', '权限管理', '权限', 'perms', '', '1', '', '0', '1', '3');

INSERT INTO SYS_FEATURE_LIST (F_ID, F_NAME, F_ABB, F_CODE, F_URL, F_TYPE, F_ICON, F_PARENT, F_VISIBLE, F_ORDER) 
VALUES ('20', '角色管理', '角色', 'role', '', '1', '', '19', '1', '31');
INSERT INTO SYS_FEATURE_OPTS (F_ID, OPT_NAME, OPT_ICON, OPT_VISIBLE, OPT_PERMS, OPT_ORDER)
VALUES ('20', '查看', '', '0', 'role:list', 1);
INSERT INTO SYS_FEATURE_OPTS (F_ID, OPT_NAME, OPT_ICON, OPT_VISIBLE, OPT_PERMS, OPT_ORDER)
VALUES ('20', '增加', '', '0', 'role:new', 2);
INSERT INTO SYS_FEATURE_OPTS (F_ID, OPT_NAME, OPT_ICON, OPT_VISIBLE, OPT_PERMS, OPT_ORDER)
VALUES ('20', '删除', '', '0', 'role:del', 3);
INSERT INTO SYS_FEATURE_OPTS (F_ID, OPT_NAME, OPT_ICON, OPT_VISIBLE, OPT_PERMS, OPT_ORDER)
VALUES ('20', '修改', '', '0', 'role:edit', 4);

INSERT INTO SYS_FEATURE_LIST (F_ID, F_NAME, F_ABB, F_CODE, F_URL, F_TYPE, F_ICON, F_PARENT, F_VISIBLE, F_ORDER) 
VALUES ('21', '用户管理', '用户', 'user', '', '1', '', '19', '1', '32');
INSERT INTO SYS_FEATURE_OPTS (F_ID, OPT_NAME, OPT_ICON, OPT_VISIBLE, OPT_PERMS, OPT_ORDER)
VALUES ('21', '查看', '', '0', 'user:list', 1);
INSERT INTO SYS_FEATURE_OPTS (F_ID, OPT_NAME, OPT_ICON, OPT_VISIBLE, OPT_PERMS, OPT_ORDER)
VALUES ('21', '增加', '', '0', 'user:new', 2);
INSERT INTO SYS_FEATURE_OPTS (F_ID, OPT_NAME, OPT_ICON, OPT_VISIBLE, OPT_PERMS, OPT_ORDER)
VALUES ('21', '删除', '', '0', 'user:del', 3);
INSERT INTO SYS_FEATURE_OPTS (F_ID, OPT_NAME, OPT_ICON, OPT_VISIBLE, OPT_PERMS, OPT_ORDER)
VALUES ('21', '修改', '', '0', 'user:edit', 4);

COMMIT;