################################################################################################################
###Spring Boot 相关组件（SpringMVC、Freemarker、Session、Cache、DataSource）配置：
################################################################################################################
spring:
  # 缓存配置：
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterAccess=600s
    redis:
      key-prefix: demo
      time-to-live: 600s
      cache-null-values: false
      use-key-prefix: true
  # 数据源配置：
  datasource:
    name: jeebiz_boot
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.170:13306/jeebiz_boot?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: jeebiz_boot
    password: hSy5aj8dD8ttTcjt
    # Druid的数据源配置：
    druid:
      #initialSize: 初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时；默认 15
      initial-size: 5
      #连接池最大连接数量
      max-active: 15
      #获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁
      max-wait: 60000
      #连接池最小连接数量；默认 5
      min-idle: 5
  # Redis相关配置
  redis:
    # Redis服务器地址
    host: 192.168.1.170
    # Redis服务器连接端口
    port: 16379
    # Database 索引；和其他服务区别开
    database: 0
    # Redis服务器连接密码（默认为空）
    password: hpkRzkC7pcDnYp3e
  # Flyway (FlywayMigrationProperties) 数据库迁移脚本版本管理（实现软件版本升级数据库自动升级）配置：
  flyway:
    enabled: true

################################################################################################################
###logging (log4j2) 基本配置：
###http://www.cnblogs.com/yhtboke/p/Mybatis.html
################################################################################################################
logging:
  config: classpath:conf/log4j2-dev.xml