################################################################################################################  
###Spring Boot 相关组件（SpringMVC、Freemarker、Session、Cache、DataSource）配置：  
################################################################################################################
spring: 
  # 缓存配置：
  cache: 
    type: ehcache
    ehcache:
      config: classpath:/conf/ehcache/ehcache.xml
  # 数据源配置：
  datasource:
    name: jeebiz_demo
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.98.123.43:3306/jeebiz_demo?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8
    username: jeebiz_demo
    password: ntzre47GiAJnL3AS
    
################################################################################################################  
###Flyway (FlywayMigrationProperties) 数据库迁移脚本版本管理（实现软件版本升级数据库自动升级）配置：  
################################################################################################################
  flyway: 
    enabled: true

################################################################################################################  
###logging (log4j2) 基本配置：  
###http://www.cnblogs.com/yhtboke/p/Mybatis.html
################################################################################################################
logging: 
  config: classpath:conf/log4j2.xml