################################################################################################################  
###Spring Boot 相关组件（SpringMVC、Freemarker、Session、Cache、DataSource）配置：  
################################################################################################################
spring:
  # 缓存配置：
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterAccess=600s
    redis:
      key-prefix: demo
      time-to-live: 600s
      cache-null-values: false
      use-key-prefix: true
  # 数据源配置：
  datasource:
    name: jeebiz_boot
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.170:13306/jeebiz_boot?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: jeebiz_boot
    password: hSy5aj8dD8ttTcjt
    # HiKariCP连接池配置：
    hikari:
      # 连接测试查询
      connection-test-query: SELECT 1
      # 连接超时时间:毫秒，小于250毫秒，否则被重置为默认值30秒
      connection-timeout: 60000
      # 一个连接的最大的生命时间（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上，参考MySQL wait_timeout参数（show variables like '%timeout%';）
      max-lifetime: 1800000
      # 连接池中允许的最大连接数。缺省值：10；大于零小于1会被重置为minimum-idle的值；推荐的公式：((core_count * 2) + effective_spindle_count)
      max-pool-size: 50
      # 最小空闲连接，默认值10，小于0或大于maximum-pool-size，都会重置为maximum-pool-size
      min-idle: 5
      # 空闲连接超时时间，默认值600000（10分钟），大于等于max-lifetime且max-lifetime>0，会被重置为0；不等于0且小于10秒，会被重置为10秒。
      idle-timeout: 500000
  # Redis相关配置
  redis:
    # Redis服务器地址
    host: 192.168.1.170
    # Redis服务器连接端口
    port: 16379
    # Database 索引；和其他服务区别开
    database: 0
    # Redis服务器连接密码（默认为空）
    password: hpkRzkC7pcDnYp3e
  # Flyway (FlywayMigrationProperties) 数据库迁移脚本版本管理（实现软件版本升级数据库自动升级）配置：
  flyway:
    enabled: true

################################################################################################################
###logging (log4j2) 基本配置：
###http://www.cnblogs.com/yhtboke/p/Mybatis.html
################################################################################################################
logging:
  config: classpath:conf/log4j2-dev.xml